- name: Copiar clave pública de sysadmin
  ansible.posix.authorized_key:
    user: sysadmin
    state: present
    key: "{{ lookup('file', sysadmin_ssh_key_path) }}"

- name: Deshabilitar login por contraseña
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
  notify: Reiniciar servidor ssh
