- name: Crear usuario ansible sin contraseña
  ansible.builtin.user:
    name: ansible
    shell: /bin/bash
    create_home: yes
    password: '!'  # Deshabilita el login por contraseña

- name: Copiar clave pública para ansible
  ansible.posix.authorized_key:
    user: ansible
    state: present
    key: "{{ lookup('file', ansible_ssh_key_path) }}"
