- name: Deshabilitar carga de m칩dulos de sistemas de archivos innecesarios
  ansible.builtin.copy:
    dest: "/etc/modprobe.d/{{ item }}.conf"
    content: "install {{ item }} /bin/true\n"
    owner: root
    group: root
    mode: '0644'
  loop:
    - cramfs
    - freevxfs
    - jffs2
    - hfs
    - hfsplus
    - squashfs
    - udf

- name: Remover m칩dulos del kernel si est치n cargados
  ansible.builtin.shell: |
    if lsmod | grep -q "^{{ item }}"; then
      rmmod {{ item }} || echo "No se pudo remover {{ item }} o no est치 cargado."
    fi
  args:
    executable: /bin/bash
  register: rmmod_results
  changed_when: false
  loop:
    - cramfs
    - freevxfs
    - jffs2
    - hfs
    - hfsplus
    - squashfs
    - udf
