- name: Asegurar que PasswordAuthentication esté habilitado
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication yes'
  notify: Reiniciar servidor ssh

- name: Configurar sshd_config para MFA
  block:
    - name: Habilitar parámetros necesarios para MFA
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^ChallengeResponseAuthentication', line: 'ChallengeResponseAuthentication yes' }
        - { regexp: '^UsePAM', line: 'UsePAM yes' }
        - { regexp: '^KbdInteractiveAuthentication', line: 'KbdInteractiveAuthentication yes' }
        - { regexp: '^PermitEmptyPasswords', line: 'PermitEmptyPasswords no' }
      notify: Reiniciar servidor ssh

- name: Crear grupo de exclusión MFA 'whitelist_nomfa'
  ansible.builtin.group:
    name: whitelist_nomfa
    state: present

- name: Agregar usuario ansible al grupo whitelist_nomfa
  ansible.builtin.user:
    name: ansible # Asegúrate de que este sea el usuario con el que te conectas
    groups: whitelist_nomfa
    append: yes

- name: Configurar PAM para SSH con MFA
  block:
    - name: Backup de /etc/pam.d/sshd
      ansible.builtin.copy:
        src: /etc/pam.d/sshd
        dest: "/etc/pam.d/sshd.bak.{{ ansible_date_time.iso8601 | regex_replace(':', '') }}"
        remote_src: yes

    - name: Aplicar configuración PAM completa con plantilla Jinja
      ansible.builtin.template:
        src: sshd.pam.j2
        dest: /etc/pam.d/sshd
        owner: root
        group: root
        mode: '0644'
        backup: yes
      notify: Reiniciar servidor ssh




