- name: Asegurar que PasswordAuthentication esté habilitado
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication yes'
  notify: Reiniciar servidor ssh

- name: Configurar sshd_config para MFA
  block:
    - name: Habilitar parámetros necesarios para MFA
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^ChallengeResponseAuthentication', line: 'ChallengeResponseAuthentication yes' }
        - { regexp: '^UsePAM', line: 'UsePAM yes' }
        - { regexp: '^KbdInteractiveAuthentication', line: 'KbdInteractiveAuthentication yes' }
        - { regexp: '^PermitEmptyPasswords', line: 'PermitEmptyPasswords no' }
  notify: Reiniciar servidor ssh

- name: Crear grupo de exclusión MFA
  ansible.builtin.group:
    name: whitelist_nomfa
    state: present

- name: Agregar usuario ansible al grupo whitelist_nomfa
  ansible.builtin.user:
    name: ansible
    groups: whitelist_nomfa
    append: yes

- name: Configurar PAM para SSH con MFA
  block:
    - name: Backup de /etc/pam.d/sshd
      ansible.builtin.copy:
        src: /etc/pam.d/sshd
        dest: "/etc/pam.d/sshd.bak.{{ ansible_date_time.iso8601 | regex_replace(':', '') }}"
        remote_src: yes

    - name: Aplicar configuración PAM para Google Authenticator
      ansible.builtin.blockinfile:
        path: /etc/pam.d/sshd
        insertafter: '^#.*Primary.*'
        block: |
          auth    [success=1 default=ignore] pam_succeed_if.so user ingroup whitelist_nomfa
          auth    required pam_google_authenticator.so
          auth    required pam_unix.so
        marker: "# {mark} ANSIBLE MFA"
  notify: Reiniciar servidor ssh

- name: Generar secreto TOTP para sysadmin
  become: true
  become_user: sysadmin
  vars:
    secret_path: "/home/sysadmin/.google_authenticator"
  block:
    - name: Crear secreto
      ansible.builtin.shell: |
        head /dev/urandom | tr -dc A-Z2-7 | head -c 16
      register: secret

    - name: Crear archivo .google_authenticator
      ansible.builtin.copy:
        dest: "{{ secret_path }}"
        content: |
          {{ secret.stdout }}
          RATE_LIMIT 3 30
          DISALLOW_REUSE
          TOTP_AUTH
          WINDOW_SIZE 3
        mode: '0600'

    - name: Generar imagen QR del TOTP
      ansible.builtin.command:
        cmd: >
          qrencode -o /home/sysadmin/mfa_qr.png
          "otpauth://totp/ServerHardening:sysadmin?secret={{ secret.stdout }}&issuer=ServerHardening&digits=6&period=30&algorithm=SHA1"
      args:
        creates: /home/sysadmin/mfa_qr.png

    - name: Copiar imagen QR al bastion
      ansible.builtin.fetch:
        src: /home/sysadmin/mfa_qr.png
        dest: ./qr/sysadmin_mfa_qr.png
        flat: yes
