- name: Asegurar que PasswordAuthentication esté habilitado
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication yes'
  notify: Reiniciar servidor ssh

- name: Configurar sshd_config para MFA
  block:
    - name: Habilitar parámetros necesarios para MFA
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^ChallengeResponseAuthentication', line: 'ChallengeResponseAuthentication yes' }
        - { regexp: '^UsePAM', line: 'UsePAM yes' }
        - { regexp: '^KbdInteractiveAuthentication', line: 'KbdInteractiveAuthentication yes' }
        - { regexp: '^PermitEmptyPasswords', line: 'PermitEmptyPasswords no' }
  notify: Reiniciar servidor ssh

- name: Crear grupo de exclusión MFA
  ansible.builtin.group:
    name: whitelist_nomfa
    state: present

- name: Agregar usuario ansible al grupo whitelist_nomfa
  ansible.builtin.user:
    name: ansible
    groups: whitelist_nomfa
    append: yes

- name: Configurar PAM para SSH con MFA
  block:
    - name: Backup de /etc/pam.d/sshd
      ansible.builtin.copy:
        src: /etc/pam.d/sshd
        dest: "/etc/pam.d/sshd.bak.{{ ansible_date_time.iso8601 | regex_replace(':', '') }}"
        remote_src: yes

    - name: Aplicar configuración PAM para Google Authenticator
      ansible.builtin.blockinfile:
        path: /etc/pam.d/sshd
        insertafter: '^#.*Primary.*'
        block: |
          auth    [success=1 default=ignore] pam_succeed_if.so user ingroup whitelist_nomfa
          auth    required pam_google_authenticator.so
          auth    required pam_unix.so
        marker: "# {mark} ANSIBLE MFA"
  notify: Reiniciar servidor ssh
