- name: Configuración de acceso
  import_tasks: access.yml

- name: Configurar sincronización horaria
  import_tasks: time_sync.yml

- name: Aplicar actualizaciones del sistema
  import_tasks: updates_upgrades.yml

- name: Instalar herramientas de seguridad y auditoría
  import_tasks: packages.yml

- name: Configurar SSH para deshabilitar login root
  import_tasks: no_ssh_root.yml

- name: Deshabilitar módulos de FyleSystem innecesarios
  import_tasks: filesystem_modules.yml

- name: Aplicar reglas auditd
  import_tasks: auditd.yml

- name: Aplicar reglas iptables
  import_tasks: iptables.yml

- name: Aplicar politicas de contraseñas
  import_tasks: password_policies.yml
