- name: Preconfigurar iptables-persistent para instalación sin intervención
  debconf:
    name: iptables-persistent
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: boolean
  loop:
    - { question: "iptables-persistent/autosave_v4", value: "true" }
    - { question: "iptables-persistent/autosave_v6", value: "false" }

- name: Instalar paquetes requeridos
  ansible.builtin.apt:
    name:
      - curl
      - wget
      - unzip
      - gnupg
      - jq
      - qrencode
      - libpam-pwquality
      - iptables
      - iptables-persistent
      - auditd
      - audispd-plugins
      - libpam-google-authenticator
      - oathtool
      - kmod
      - libpam-modules-bin
    state: present
    update_cache: yes
  register: resultado_apt

- name: Mostrar resumen de instalación
  ansible.builtin.debug:
    msg: >
      {% if resultado_apt.changed %}
      ✅ Se instalaron o actualizaron paquetes.
      {% else %}
      ✅ Todos los paquetes ya estaban instalados.
      {% endif %}

- name: Mostrar paquetes requeridos
  ansible.builtin.debug:
    msg: |
      📦 Paquetes requeridos:
      {% for pkg in (resultado_apt['invocation']['module_args']['name'] if 'invocation' in resultado_apt and 'module_args' in resultado_apt['invocation'] else []) %}
        - {{ pkg }}
      {% endfor %}
