- name: Limpiar registros de faillock y tally2 (si existen)
  ansible.builtin.shell: |
    faillock --reset || true
    pam_tally2 --reset || true
    rm -f /var/run/faillock/* /var/lib/faillock/* || true
  args:
    executable: /bin/bash

- name: Backup y configurar pwquality.conf
  block:
    - name: Crear backup de pwquality.conf
      ansible.builtin.copy:
        src: /etc/security/pwquality.conf
        dest: "/etc/security/pwquality.conf.bak.{{ ansible_date_time.iso8601 | regex_replace(':', '') }}"
        remote_src: yes

    - name: Limpiar configuraciones previas en pwquality.conf
      ansible.builtin.lineinfile:
        path: /etc/security/pwquality.conf
        regexp: '^(minlen|minclass|dcredit|ucredit|ocredit|lcredit)\s*='
        state: absent

    - name: Establecer política de complejidad en pwquality.conf
      ansible.builtin.blockinfile:
        path: /etc/security/pwquality.conf
        block: |
          minlen = 14
          minclass = 4
          dcredit = -1
          ucredit = -1
          ocredit = -1
          lcredit = -1
        marker: "# {mark} ANSIBLE pwquality hardening"

- name: Backup y configurar common-password
  block:
    - name: Crear backup de common-password
      ansible.builtin.copy:
        src: /etc/pam.d/common-password
        dest: "/etc/pam.d/common-password.bak.{{ ansible_date_time.iso8601 | regex_replace(':', '') }}"
        remote_src: yes

    - name: Eliminar líneas previas pam_pwquality y pam_unix
      ansible.builtin.lineinfile:
        path: /etc/pam.d/common-password
        regexp: 'pam_(pwquality|unix)\.so'
        state: absent

    - name: Insertar reglas de pam_pwquality y pam_unix en common-password
      ansible.builtin.blockinfile:
        path: /etc/pam.d/common-password
        insertafter: '^# here are the per-package modules \(the "Primary" block\)'
        block: |
          password requisite pam_pwquality.so retry=3
          password [success=1 default=ignore] pam_unix.so obscure use_authtok yescrypt sha512
        marker: "# {mark} ANSIBLE PAM hardening"
